### PR TITLE
Ramiz branch 01

### PR DESCRIPTION
**Pull request by ramizkazak**
fixed User stroy4 test case2

### CODE REVIEW

**Comment by GuvanchH** [comment]
Looks Good

**Review by asuman75 — APPROVED** [review]
good job

**Review by asuman75 — APPROVED** [review]
hi

**Review by asuman75 — APPROVED** [review]
well done

**Review by altyshaibraim — APPROVED** [review]
thanks

**Review by MedSdiri — APPROVED** [review]
good ramiz

**Pull request merged**
