### PR TITLE
Anna`s 4th commit:

### PR DESCRIPTION
**Pull request by avsank**
-added ActivityPage (under Page Components).

Merge remote-tracking branch 'origin/master'

### CODE REVIEW

**Review by ramizkazak — APPROVED** [review]
Looks good,
Nice work
well done

**Review by ercancivi — APPROVED** [review]
nice job

**Review by AzadBatch21 — APPROVED** [review]
Done!

**Review by MedSdiri — APPROVED** [review]
good job Anna

**Pull request merged**
