### PR TITLE
Ramiz branch 01

### PR DESCRIPTION
**Pull request by ramizkazak**
So far for our project

### CODE REVIEW

**Review by AzadBatch21 — APPROVED** [review]
Approved bro!

**Comment by ercancivi** [comment]
thank for finishin on time

**Review by ercancivi — APPROVED** [review]
nice

**Review by IrinaMakaryan — APPROVED** [review]
awesome job

**Comment by GuvanchH** [comment]
Good

**Comment by ercancivi** [comment]
Hello hello

**Pull request merged**
